middleware:
  address: 172.16.12.131

spring:

  cloud:
    nacos:
      discovery:
        server-addr: ${middleware.address}:8848

  zipkin:
    #enabled: true
    sender:
      type: rabbit
    base-url: http://localhost:9411/
    service:
      name: provider
  sleuth:
    sampler:
      probability: 1 #???????? 0.1 ????????percentage ??????? probability
  rabbitmq:
    host: ${middleware.address}
    port: 5672
    username: guest
    password: guest
    listener: # ?????????
      direct:
        retry:
          enabled: true