server:
  port: 8762

spring:
  application:
    name: provider

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  zipkin:
    #enabled: true
    sender:
      type: web
    base-url: http://localhost:9411/
    service:
      name: provider
  sleuth:
    sampler:
      probability: 1 #设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability