server:
  port: 8763

spring:
  profiles:
    active: dev
  application:
    name: consumer

#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mybatis/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: consumer.entity
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false


